rebaseMergeAllowed: false
squashMergeAllowed: true
mergeCommitAllowed: false
deleteBranchOnMerge: true
branchProtectionRules:
- pattern: main
  isAdminEnforced: true
  requiredApprovingReviewCount: 1
  requiresCodeOwnerReviews: true
  requiresStrictStatusChecks: false
  requiredStatusCheckContexts:
    - cla/google
    - "Workload 7 AWK Postprocessing / build (pull_request)"
    - "Workload 7 Cloud Function / build (pull_request) "

